package main

import (
	"bufio"
	"log"
	"os"
	"strconv"
	"github.com/rabbitmq/amqp091-go"
	"strings"
	"math/rand/v2"
)

func main() {
	// connect to RMQ
	conn, err := amqp091.Dial("amqp://guest:guest@localhost:5672/")

	if err != nil {
		log.Fatalln("Failed to connect to RabbitMQ:", err)
	}
	defer conn.Close()

	ch, err := conn.Channel()
	if err != nil {
		log.Fatalln("Failed to open a channel:", err)
	}
	defer ch.Close()

	// Declare a temp queue for receiving responses, with a unique name generated by the server
	q, err := ch.QueueDeclare(
		"",
		false,
		false,
		true, // we want the queue to be deleted when the connection is closed
		false,
		nil,
	)
	if err != nil {
		log.Fatalln("Failed to declare a queue:", err)
	}

	// Generate a unique correlation ID for this request, this will be used to match the response with the request
	corrID := strconv.Itoa(rand.Int())
	log.Println("Generated correlation ID:", corrID)

	reader := bufio.NewReader(os.Stdin)
	log.Print("Type a message to send to RabbitMQ (type 'quit' to exit)")

	for {
		log.Println("Enter message: ")
		input, err := reader.ReadString('\n')
		if err != nil {
			log.Println("Error reading input:", err)
			return
		}
		input = strings.TrimSpace(input)
		if strings.ToLower(input) == "quit" {
			log.Println("Exiting...")
			return
		}

		err = ch.Publish("", "q.rpc", false, false, amqp091.Publishing{
			ContentType:   "text/plain",
			CorrelationId: corrID,
			ReplyTo:       q.Name,
			Body:          []byte(input),
		})
		if err != nil {
			log.Println("Failed to publish message:", err)
			return
		}

		log.Println("Sent message:", input)

		msgs, err := ch.Consume(q.Name, "", true, false, false, false, nil)
		if err != nil {
			log.Println("Failed to consume messages:", err)
			return
		}

		for msg := range msgs {
			if msg.CorrelationId == corrID {
				log.Println("Received response:", string(msg.Body))
				break
			}
		}
	}

}