package main

import (
	"context"
	"errors"
	"fmt"
	"sync"

	rmq "github.com/rabbitmq/rabbitmq-amqp-go-client/pkg/rabbitmqamqp"
)

func main() {
	exchangeName := "x.amqp1.fanout"
	stateChanged := make(chan *rmq.StateChanged, 1)
	var wg sync.WaitGroup

	ctxB := context.Background()

	rmq.Info("Creating connection to RabbitMQ")

	env := rmq.NewEnvironment("amqp://guest:guest@localhost:5672/", nil)
	
	conn, err := env.NewConnection(ctxB)
	if err != nil {
		rmq.Error("Failed to create connection: %v", err)
		return
	}
	conn.NotifyStatusChange(stateChanged)

	wg.Add(1)
	go func() {
		defer wg.Done()
		for statusChanged := range stateChanged {
			fmt.Printf("Connection status changed: %s\n", statusChanged)

		}
	}()

	management := conn.Management()
	_, err = management.DeclareExchange(ctxB, &rmq.FanOutExchangeSpecification{
		Name: exchangeName,
	})
	if err != nil {
		rmq.Error("Failed to declare exchange: %v", err)
		return
	}

	q, err := management.DeclareQueue(ctxB, &rmq.AutoGeneratedQueueSpecification{
		IsAutoDelete: true,
		IsExclusive: true,
	})
	if err != nil {
		rmq.Error("Failed to declare queue: %v", err)
		return
	}

	_, err = management.Bind(ctxB, &rmq.ExchangeToQueueBindingSpecification{
		SourceExchange: exchangeName,
		DestinationQueue: q.Name(),
	})
	if err != nil {
		rmq.Error("Failed to bind queue to exchange: %v", err)
		return
	}

	consumer, err := conn.NewConsumer(ctxB, q.Name(), nil)
	if err != nil {
		rmq.Error("Failed to create consumer: %v", err)
		return
	}

	ctxBC, cancel := context.WithCancel(ctxB)
	defer cancel()
	
	wg.Add(1)
	go func() {
		defer wg.Done()
		for {
			deliveryContext, err := consumer.Receive(ctxBC)
			if errors.Is(err, context.Canceled) {
				rmq.Info("Context canceled, stopping consumer")
				break
			} else if err != nil {
				rmq.Error("Failed to receive message: %v", err)
				continue
			}

			rmq.Info("Received message: ", fmt.Sprintf("%s", deliveryContext.Message().Data))
			err = deliveryContext.Accept(ctxB)
			if err != nil {
				rmq.Error("Failed to accept message: %v", err)
			}

		
		}
	}()


	fmt.Println("Waiting for incoming messages. Press enter to close the consumer")
	_, err = fmt.Scanln()
	if err != nil {
		rmq.Error("Failed to read input: %v", err)
		return
	}

	cancel()

	err = consumer.Close(ctxB)
	if err != nil {
		rmq.Error("Failed to close consumer: %v", err)
		return
	}

	err = env.CloseConnections(ctxB)
	if err != nil {
		rmq.Error("Failed to close connections: %v", err)
		return
	}

	wg.Wait()
	close(stateChanged)

}